import Head from "next/head";
import { useState } from "react";
import { Container } from "../components/sharedstyles";
import styled from "styled-components";

export default function Home() {
  const [input, setInput] = useState("");
  const [result, setResult] = useState("");
  const [conversation, setConversation] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  async function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsLoading(true);
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          conversation: conversation
            .map((sentence, i) => (i % 2 === 0 ? `Me: ${sentence}` : `You: ${sentence}`))
            .join("\n"),
          input: input,
        }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }

      setResult(data.result);
      setConversation([...conversation, input, data.result.replace(/^\s+|\s+$|\n+/g, "")]);
      setInput("");
      setIsLoading(false);
    } catch (error) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
      setIsLoading(false);
    }
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title>OpenAI PoC</Title>
      <Logo src='/logo.png' />
      {isLoading && <Loading>Loading...</Loading>}
      {result && !isLoading && <Result>{result}</Result>}
      <Form onSubmit={onSubmit}>
        <InputField type='text' value={input} onChange={(e) => setInput(e.target.value)} />
        <SubmitButton disabled={isLoading} type='submit' value={"Submit"} />
      </Form>
    </Container>
  );
}

const Title = styled.h1`
  margin-bottom: 20px;
  font-size: 20px;
  text-align: center;
  text-decoration: none;
`;

const Logo = styled.img`
  margin-bottom: 30px;
  width: 80px;
`;

const Loading = styled.div`
  margin-bottom: 20px;
`;

const Result = styled.div`
  padding: 10px;
  max-width: 400px;
  border: solid 1px #666;
  border-radius: 10px;
  margin-bottom: 20px;
  text-align: center;
`;

const Form = styled.form`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const InputField = styled.input`
  margin-bottom: 30px;
  width: 400px;
  padding: 12px;
  border-radius: 8px;
  border: 2px solid ${({ theme }) => theme.colors.secondary};
  font-size: 16px;
  transition: border-color 0.2s ease-in-out;

  &:focus {
    border-color: ${({ theme }) => theme.colors.primary};
    outline: none;
  }
`;

const SubmitButton = styled.input`
  padding: 12px;
  border-radius: 8px;
  border: none;
  background-color: ${({ theme }) => theme.colors.primary};
  color: #fff;
  font-size: 16px;
  font-weight: bold;
  transition: background-color 0.2s ease-in-out;
  cursor: pointer;

  &:hover {
    background-color: #0066cc;
  }

  &[disabled] {
    cursor: not-allowed;
  }
`;
