import Head from "next/head";
import { Container } from "../components/sharedstyles";
import styled from "styled-components";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title>OpenAI PoC</Title>
      <Logo src='/logo.png' />
      <InputField type='text' />
      <SubmitButton>전송하기</SubmitButton>
    </Container>
  );
}

const Title = styled.h1`
  margin-bottom: 20px;
  font-size: 20px;
  text-align: center;
  text-decoration: none;
`;

const Logo = styled.img`
  margin-bottom: 30px;
  width: 80px;
`;

const InputField = styled.input`
  margin-bottom: 30px;
  padding: 12px;
  border-radius: 8px;
  border: 2px solid #ccc;
  font-size: 16px;
  transition: border-color 0.2s ease-in-out;

  &:focus {
    border-color: #1e90ff;
    outline: none;
  }
`;

const SubmitButton = styled.button`
  padding: 12px;
  border-radius: 8px;
  border: none;
  background-color: #1e90ff;
  color: #fff;
  font-size: 16px;
  font-weight: bold;
  cursor: pointer;
  transition: background-color 0.2s ease-in-out;

  &:hover {
    background-color: #0066cc;
  }

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
`;
